pipeline {
    agent any

    tools {
        maven 'Maven 3.9.6'     
        jdk 'jdk-17'            
    }

    environment {
        SONARQUBE_TOKEN = credentials('springbootapp-token')
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build and Test') {
            steps {
                sh 'cd demo && mvn clean install'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('MySonarQube') {
                    sh '''
                        cd demo
                        mvn sonar:sonar \
                          -Dsonar.projectKey=SpringBootApp \
                          -Dsonar.projectName=SpringBootApp \
                          -Dsonar.projectVersion=1.0 \
                          -Dsonar.java.binaries=target/classes \
                          -Dsonar.sources=src/main/java
                    '''
                }
            }
        }

        stage('Deploy WAR to Tomcat') {
            steps {
                sh '''
                    cd demo
                    curl --upload-file target/*.war "http://admin:admin123@localhost:5050/manager/text/deploy?path=/SpringBootApp&update=true"
                '''
            }
        }
    }

    post {
        always {
            echo 'Pipeline Completed!'
        }
    }
}